# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Wed Jun  1 21:42:19 2022)---
runfile('C:/Users/prochula/.spyder-py3/temp.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/checkProfit.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/signal.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/temp2.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/signal.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/apibutkib.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/signal.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/apibutkib.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/signal.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/apibutkib.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/tempAsync.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runcell(0, 'C:/Users/prochula/.spyder-py3/toei.py')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/temp2.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/test.py', wdir='C:/Users/prochula/.spyder-py3')
runfile('C:/Users/prochula/.spyder-py3/toei.py', wdir='C:/Users/prochula/.spyder-py3')